#!/usr/bin/env bash
# a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
for p in *; do paste - - | cut -f1 '-' -p 2; done
